### ISSUE TITLE
cuda runtime error 

### ISSUE THREAD

**Issue by RMobina** [yysijie/st-gcn#15]
Hi,
I tried to evaluate ST-GCN model pretrained on NTU RGB dataset but I recieved this error:

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58

**this is my complete output:**
python main.py --config config/st_gcn/nturgbd-cross-view/test.yaml
[ Thu Mar 29 12:40:17 2018 ] Load weights from ./model/ntuxview-st_gcn.pt.
[ Thu Mar 29 12:40:17 2018 ] Model:   st_gcn.net.ST_GCN.
[ Thu Mar 29 12:40:17 2018 ] Weights: ./model/ntuxview-st_gcn.pt.
[ Thu Mar 29 12:40:17 2018 ] Eval epoch: 1
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 344, in eval
    output = self.model(data)
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/st_gcn.py", line 153, in forward
    x = m(x)
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/st_gcn.py", line 210, in forward
    x = self.tcn1(self.gcn1(x)) + (x if
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/unit_gcn.py", line 84, in forward
    y = y + self.conv_list[i](xa)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58
(tensorflow141) razieh@Razieh:~/eclipse-workspace/CNN_Skeleton_NTURGB$ python main.py --config config/st_gcn/nturgbd-cross-view/test.yaml
[ Thu Mar 29 12:56:18 2018 ] Load weights from ./model/ntuxview-st_gcn.pt.
[ Thu Mar 29 12:56:18 2018 ] Model:   st_gcn.net.ST_GCN.
[ Thu Mar 29 12:56:18 2018 ] Weights: ./model/ntuxview-st_gcn.pt.
[ Thu Mar 29 12:56:18 2018 ] Eval epoch: 1
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 344, in eval
    output = self.model(data)
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/st_gcn.py", line 153, in forward
    x = m(x)
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/st_gcn.py", line 210, in forward
    x = self.tcn1(self.gcn1(x)) + (x if
  File "/home/razieh/miniconda3/envs/tensorflow141/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/razieh/eclipse-workspace/CNN_Skeleton_NTURGB/st_gcn/net/unit_gcn.py", line 84, in forward
    y = y + self.conv_list[i](xa)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58

**Could you please guide me how can I solve this problem.**
thank you

**Comment by zhezh** [comment]
use `nvidia-smi` to check if you have enough gpu memory available

**Comment by RMobina** [comment]
I changed the batch size number and it worked. 
thanks
