### ISSUE TITLE
RuntimeError: cuda runtime error (59) :device-side assert triggered at /pytorch/aten/src/THC/generic/THCStorage.cpp:36

### ISSUE THREAD

**Issue by wwwpbai** [yysijie/st-gcn#157]
@yysijie , @xiaoyuliu , i train my dataset which has 51 classes, when training it occured error.but i revise number of  classes which is larger than 51 it can train normally

**Comment by wwwpbai** [comment]
[03.22.19|17:18:42] Parameters:
{'work_dir': './work_dir/recognition/kinetics_skeleton/ST_GCN', 'config': 'config/st_gcn/kinetics-skeleton/train.yaml', 'phase': 'train', 'save_result': False, 'start_epoch': 0, 'num_epoch': 50, 'use_gpu': True, 'device': [0], 'log_interval': 100, 'save_interval': 10, 'eval_interval': 5, 'save_log': True, 'print_log': True, 'pavi_log': False, 'feeder': 'feeder.feeder.Feeder', 'num_worker': 4, 'train_feeder_args': {'random_choose': True, 'random_move': True, 'window_size': 150, 'data_path': './data/Kinetics/kinetics-skeleton/train_data.npy', 'label_path': './data/Kinetics/kinetics-skeleton/train_label.pkl', 'debug': False}, 'test_feeder_args': {'data_path': './data/Kinetics/kinetics-skeleton/val_data.npy', 'label_path': './data/Kinetics/kinetics-skeleton/val_label.pkl'}, 'batch_size': 32, 'test_batch_size': 32, 'debug': False, 'model': 'net.st_gcn.Model', 'model_args': {'in_channels': 3, 'num_class': 51, 'edge_importance_weighting': True, 'graph_args': {'layout': 'openpose', 'strategy': 'spatial'}}, 'weights': None, 'ignore_weights': [], 'show_topk': [1, 5], 'base_lr': 0.1, 'step': [20, 30, 40, 50], 'optimizer': 'SGD', 'nesterov': True, 'weight_decay': 0.0001}

[03.22.19|17:18:42] Training epoch: 0
[rec]:train
[03.22.19|17:18:42] 	Iter 0 Done. | loss: 3.9210 | lr: 0.100000
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cpp line=36 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    p.start()
  File "/home/smarket/st-gcn/processor/processor.py", line 119, in start
    self.train()
  File "/home/smarket/st-gcn/processor/recognition.py", line 102, in train
    self.iter_info['loss'] = loss.data.item()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCStorage.cpp:36

**Comment by wwwpbai** [comment]
I solved it, the index of my label file is starting from one, i set it zero then i trained it normally.

**Comment by saniazahan** [comment]
Hey @wwwpbai how did you set the starting to zero, I am facing the same problem. Thanks.
