### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by taxuezcy** [yysijie/st-gcn#61]
@yysijie @yjxiong  ，when i train the  model ,the error is 
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/cloud/st-gcn-master/processor/processor.py", line 113, in start
    self.train()
  File "/home/cloud/st-gcn-master/processor/recognition.py", line 91, in train
    output = self.model(data)
  File "/home/cloud/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cloud/st-gcn-master/net/st_gcn.py", line 82, in forward
    x, _ = gcn(x, self.A * importance)
  File "/home/cloud/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cloud/st-gcn-master/net/st_gcn.py", line 194, in forward
    x, A = self.gcn(x, A)
  File "/home/cloud/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cloud/st-gcn-master/net/utils/tgcn.py", line 60, in forward
    x = self.conv(x)
  File "/home/cloud/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cloud/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
however, the size of the dataset i use is only  180MB, so how can i fix this problem?

**Comment by yysijie** [comment]
@taxuezcy,
This is caused by your GPU memory but not the CPU memory.
Please decrease the batch size and test bach size by this command:
`python main.py recognition -c config/st_gcn/kinetics-skeleton/train.yaml --batch_size 8 --test_batch_size 8
`

**Comment by taxuezcy** [comment]
@yysijie ,what a coincidence! i have just fixed the problem by setting the the batch size 16 and then i receive you reply, any way ,thank you very much  for you kind  reply!

**Comment by yysijie** [comment]
@taxuezcy 
That's great!
